---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyr)
library(dplyr)
library(tidyverse)
library(lubridate)
```

```{r}
dataa <- readRDS("data_aggregated.rds")
```

# determining the most unsafe times to drive based on speeding occurances
```{r}
speed_shift_data <- dataa %>% 
  mutate(hour = as.integer(format(timestamp, format = "%H"))) %>% 
  select(hour, speed, road_speed) %>% 
  filter(speed > road_speed) %>% 
  group_by(hour) %>% 
  mutate(total = n()) %>% 
  select(-speed, -road_speed) %>% 
  arrange(hour) %>% 
  ungroup()

speed_shift_data <- unique(speed_shift_data)
  
```

# obtaining average risk rating per each car's driving shift period
# key: > 20,000 == 10, > 10,000 == 9, = 8000 == 8, = 7000 == 7, etc..
```{r}
shift_data <- dataa %>% 
  select(vehicleid, timestamp) %>% 
  mutate(hour = as.integer(format(timestamp, format = "%H"))) %>% 
  mutate(shift_risk = case_when(hour == 0 ~ 5,
                                 hour == 1 ~ 1,
                                 hour == 2 ~ 2,
                                 hour == 3 ~ 4,
                                 hour == 4 ~ 8,
                                 hour == 5 ~ 9,
                                 hour == 6 ~ 10,
                                 hour == 7 ~ 10,
                                 hour == 8 ~ 9,
                                 hour == 9 ~ 8,
                                 hour == 10 ~ 8,
                                 hour == 11 ~ 5,
                                 hour == 12 ~ 5,
                                 hour == 13 ~ 7,
                                 hour == 14 ~ 8,
                                 hour == 15 ~ 9,
                                 hour == 16 ~ 9,
                                 hour == 17 ~ 9,
                                 hour == 18 ~ 9,
                                 hour == 19 ~ 9,
                                 hour == 20 ~ 9,
                                 hour == 21 ~ 8,
                                 hour == 22 ~ 7,
                                 hour == 23 ~ 6)) %>%
   group_by(vehicleid) %>% 
   summarise(shift_risk = mean(shift_risk)) %>% 
   ungroup()
shift_data

saveRDS(shift_data, "shift_risk.rds")
```

